--PARTICIONAMIENTO 
/*CLAVE DE PARTICIONAMIENTO:
ES LA CLAVE QUE DETERMINA LA PARTICION EN LA QUE TERMINA UNA FILA
ESTA FORMADA POR UNA O MAS COLOMNAS Y ORACLE DETRMINA SU UBICACION DE FORMA AUTOMATICA

EXISTEN DOS ESTRATEGIA DE PARTICION:
SIMPLE: SE IMPLEMENTA UN SOLO TIPO DE PARTICIONAMIENTO
COMPUESTO: SE COMBINAN PARTICIONAMIENTOS

TIPOS DE PARTICIONAMIENTOS
RANGO:SE BASA EN RANGOS CONCRETOS DE VALORES
ES EL MAS HABITUAL Y SUELE ESTAR BASADOS EN FECHAS
HAY UNA CLAUSULA "MAXVALUE" QUE IDENTIFICA UN LIMITE SUPERIOR DE TIPO INFINITO.

LISTA: INDICAMOS UNA LISTA DE VALORES PARA CADA PARTICION
PODEMOS TENER UNA PARTICION DE TIPO "DEFAULT" A DONDE VAN A PARAR 
LAS FILAS QUE NO ENCAJAN EN OTRA.


HASH: CADA PARTICION ESTA BASADA EN UN ALGORITMO DE TIPO HASHING.
ESTO PERMITE DISTRIBUIR LOS DATOS DE FORMA MUY HOMOGENEA (IGUAL)
LAS FILAS ACABAN DIMEPRE EN UNA PARTICION.

COMPUESTO: EN ESTE CASO LA TABLA SE DIVIDE POR UN METODO DE PARTICIONAMIENTO Y LUEGO
CADA PARTICION SE DIVIDE EN SUB-PARTICION CON OTRO METODO.
HAY VARIAS ALTERNATIVAS.

RANGO-RANGO
RANGO-HASH
RANGO-LISTA
*/

CREATE TABLE RANGO(
CODIGO NUMBER NOT NULL,
NOMBRE VARCHAR2(50)
)
PARTITION BY RANGE(CODIGO)(
PARTITION P1 VALUES LESS THAN (10),
PARTITION P2 VALUES LESS THAN (20),
PARTITION P3 VALUES LESS THAN (30),
PARTITION P4 VALUES LESS THAN (40)
);

SELECT * FROM RANGO;

SELECT * FROM USER_PART_TABLES;

SELECT * FROM user_tab_partitions;

INSERT INTO RANGO VALUES(40,'SASKDAF');

SELECT * FROM RANGO;

SELECT * FROM RANGO PARTITION(P3);

INSERT INTO RANGO VALUES(8,'SDSAADAF');

SELECT * FROM RANGO PARTITION(P1);

--AGREGAR OTRA PARTICION PARA AGREGAR UNA PARTICION SIEMPRE 
--DEBE SER MAYOR A LA ULTIMA PARTICION

ALTER TABLE RANGO
ADD PARTITION P6 VALUES LESS THAN (100);

SELECT * FROM user_tab_partitions;

--ESTA PARTICION NO TIENE FIN
ALTER TABLE RANGO
ADD PARTITION P8 VALUES LESS THAN (MAXVALUE);

--POR EJEMPLO SI QUEREMOS MODIFICAR EL CODIGO DE UNA TABLA SE PUEDE HCAER MIENTRAS
--QUE NO LA CAMBIE DE PARTICION .

UPDATE RANGO SET CODIGO= 22 WHERE CODIGO=21;

--DARA UN ERROR SI QUIERO CAMBIAR DE PARTICION

UPDATE RANGO SET CODIGO= 7 WHERE CODIGO=22;

--SE VA A PODER CAMBIAR DE PARTICION SI PONGO EL SIGUIENTE CODIGO
--SIGNIFICA QUIERO QUE ME PERMITAS HACER MOVIMIENTO DE FILAS
--TAMBIEN TIENE PERDIDA DE RENDIMIENTO

ALTER TABLE RANGO ENABLE ROW MOVEMENT;


--FUSION DE PARTIOCIONES SE LAS PUEDE REALIZAR SI ESTAN UNA AL LADO DE OTRA OSEA
--ADYACENTES

ALTER TABLE RANGO MERGE PARTITIONS P3,P4 INTO PARTITION P3_4;

-- FUSIONAR VARIAS PARTICIONES

ALTER TABLE RANGO MERGE PARTITIONS P5 TO P8 INTO PARTITION P5_8;







